sudo: false
language: php

php:
  - 7.3
  - 7.4
  - 8.0
matrix:
    allow_failures:
        - php: 7.2

before_script:
  - composer self-update
  - composer install
  - phpenv rehash

script:
  - ./vendor/bin/phpunit --coverage-text
